@startuml

object CORP_TYPE {
	CORP_TYP_CD
}

object CORP_OP_STATE {
	STATE_TYP_CD
}

object CORP_STATE {
	CORP_NUM
	STATE_TYP_CD
}

object CORPORATION {
	CORP_NUM
	CORP_TYP_CD
}

object CORP_NAME_TYPE {
	CORP_NAME_TYP_CD
}

object CORP_NAME {
	CORP_NUM
	CORP_NAME_TYP_CD
}

object OFFICE_TYPE {
	OFFICE_TYP_CD
}

object OFFICE {
	CORP_NUM
	OFFICE_TYP_CD
	MAILING_ADDR_ID
	DELIVERY_ADDR_ID
}

object TILMA_INVOLVED {
	CORP_NUM
}

object ADDRESS {
	ADDR_ID
}

object JURISDICTION {
	CORP_NUM
	CAN_JUR_TYP_CD
	XPRO_TYP_CD
}

object JURISDICTION_TYPE {
	CAN_JUR_TYP_CD
}

object XPRO_TYPE {
	XPRO_TYP_CD
}

object EVENT {
	EVENT_ID
}

object FILING {
	FILING_ID
	EVENT_ID
}

CORP_TYPE "1" -down- "0..*" CORPORATION
CORP_STATE "1..*" -down- "1" CORPORATION
CORP_OP_STATE "1" -down- "0..*" CORP_STATE

CORPORATION "1" -up- "1..*" OFFICE

CORPORATION "1" -right- "1..*" CORP_NAME : org_name
note on link : where CORP_NAME_TYP_CD in ('CO','NB')
CORPORATION "1" -right- "0..*" CORP_NAME : org_name_assumed
note on link : where CORP_NAME_TYP_CD in ('AS')
CORPORATION "1" -right- "0..*" CORP_NAME : org_name_trans
note on link : where CORP_NAME_TYP_CD in ('TR', 'NO')

CORPORATION "1" -down- "0..*" TILMA_INVOLVED
CORPORATION "1" -down- "0..*" JURISDICTION
JURISDICTION "0..*" -down- "1" JURISDICTION_TYPE
JURISDICTION "0..*" -down- "1" XPRO_TYPE

OFFICE -[hidden]down- CORP_NAME

CORP_NAME_TYPE "1" -left- "0..*" CORP_NAME

OFFICE_TYPE "1" -- "0..*" OFFICE
note on link : office_typ_cd in ('RG','HD','FO')

OFFICE "1" -right- "1..*" ADDRESS : DELIVERY_ADDR_ID
OFFICE "1" -right- "0..*" ADDRESS : MAILING_ADDR_ID

EVENT "1..*" -right- "1" CORPORATION
EVENT "1" -down- "0..1" FILING

@enduml
