@startuml

package Tracking {
object EVENT_BY_FILING_TYP
EVENT_BY_FILING_TYP : EVENT_ID
EVENT_BY_FILING_TYP : FILING_TYPE

object EVENT_BY_CORP_FILING
EVENT_BY_CORP_FILING : EVENT_ID
EVENT_BY_CORP_FILING : FILING_TYPE
EVENT_BY_CORP_FILING : CORP_NUM
}

package Configuration {
object CREDENTIAL_SCHEMA {
  CREDENTIAL_TYP_CD
  CREDENTIAL_NAME
  CREDENTIAL_SCHEMA
}

object EVENT_CREDENTIAL_MAP {
  EVENT_TYP_CD
  FILING_TYP_CD
  CREDENTIAL_TYP_CD
  MAPPING_SCRIPT
}
}

object EVENT_LOG {
  EVENT_ID
  FILING_TYPE
  CORP_NUM
  FILING_DATA
  CREDS_DATA
  EVENT_DATE
  CREATED_DATE
  PROCESSED_DATE
}

object CREDENTIAL_LOG {
  EVENT_ID
  FILING_TYPE
  CORP_NUM
  CREDENTIAL_TYP_CD
  CREDS_DATA
  CREATED_DATE
  PROCESSED_DATE
}

Tracking -[hidden]down-> Configuration
Tracking -[hidden]right-> EVENT_LOG
Configuration -[hidden]right-> CREDENTIAL_LOG

@enduml
