@startuml

folder BC_Registries {
  database BC_Registries_DB
  database Event_Monitor_DB
}

BC_Registries_DB -up-> Event_Monitor_DB

folder Event_Processor {
  folder Event_Batch {
    node Monitor_Events
    node Cache_Corporations
    node Load_Corporations
    node Generate_Credentials
    node Submit_Credentials
  }

  Monitor_Events -[hidden]down-> Cache_Corporations
  Cache_Corporations -[hidden]down-> Load_Corporations
  Load_Corporations -[hidden]down-> Generate_Credentials
  Generate_Credentials -[hidden]down-> Submit_Credentials

  database Corp_Event_DB
  database Corp_Cache_DB
  database Corp_JSON_DB
  database Credential_JSON_DB

  Corp_Event_DB -[hidden]down-> Corp_Cache_DB
  Corp_Cache_DB -[hidden]down-> Corp_JSON_DB
  Corp_JSON_DB -[hidden]down-> Credential_JSON_DB
}

note top of Monitor_Events
Monitor log file and generate Events
Monitor_Events fetches data from Registries DB
end note

Event_Monitor_DB -right-> Monitor_Events
Monitor_Events -right-> Corp_Event_DB

Corp_Event_DB --> Cache_Corporations
BC_Registries_DB -right-> Cache_Corporations
Cache_Corporations -right-> Corp_Cache_DB

Corp_Cache_DB --> Load_Corporations
Load_Corporations -right-> Corp_JSON_DB

Corp_JSON_DB --> Generate_Credentials
Generate_Credentials -right-> Credential_JSON_DB

folder VON_X {
  node VON_API
  database VON_Wallet
}

Credential_JSON_DB --> Submit_Credentials
Submit_Credentials -right-> VON_API

note top of Event_Processor
For each input Event:
  - Identify Event Type
  - Identify the corresponding Credential Type(s)
  - Fetch all Credential attributes from source database ***
  - Create output Credential(s) and send to Von_X
  - Track issued Credentials to support future re-issue, revocation, etc.
end note


VON_API -down-> VON_Wallet

folder T_O_B {
  node TOB_API
  database TOB_Wallet
}

TOB_API -down-> TOB_Wallet

folder Sovrin_Network {
  node Distributed_Ledger
}

VON_API -down-> Distributed_Ledger
VON_API -right-> TOB_API
TOB_API -down-> Distributed_Ledger
VON_Wallet -[hidden]down-> Distributed_Ledger
TOB_Wallet -[hidden]down-> Distributed_Ledger

@enduml
