@startuml

object LAST_EVENT {
  SYSTEM_TYPE_CD
  EVENT_ID
  EVENT_DATE
}

object EVENT_BY_CORP_FILING {
  SYSTEM_TYPE_CD
  CORP_NUM
  PREV_EVENT_ID
  LAST_EVENT_ID
  PROCESS_DATE
}

object EVENT_BY_CORP_FILING {
  SYSTEM_TYPE_CD
  CORP_NUM
  CORP_STATE
  PREV_EVENT
  LAST_EVENT
  CORP_JSON
  PROCESS_DATE
}

object CREDENTIAL_LOG {
  SYSTEM_TYPE_CD
  CORP_NUM
  EVENT_ID
  CORP_STATE
  PREV_EVENT
  LAST_EVENT
  SCHEMA_ID
  SCHEMA_VERSION
  CREDENTIAL_JSON
  PROCESS_DATE
}

@enduml
